// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/768bit/promethium/api/models"
)

// NewCreateStorageParams creates a new CreateStorageParams object
// with the default values initialized.
func NewCreateStorageParams() *CreateStorageParams {
	var ()
	return &CreateStorageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateStorageParamsWithTimeout creates a new CreateStorageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateStorageParamsWithTimeout(timeout time.Duration) *CreateStorageParams {
	var ()
	return &CreateStorageParams{

		timeout: timeout,
	}
}

// NewCreateStorageParamsWithContext creates a new CreateStorageParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateStorageParamsWithContext(ctx context.Context) *CreateStorageParams {
	var ()
	return &CreateStorageParams{

		Context: ctx,
	}
}

// NewCreateStorageParamsWithHTTPClient creates a new CreateStorageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateStorageParamsWithHTTPClient(client *http.Client) *CreateStorageParams {
	var ()
	return &CreateStorageParams{
		HTTPClient: client,
	}
}

/*CreateStorageParams contains all the parameters to send to the API endpoint
for the create storage operation typically these are written to a http.Request
*/
type CreateStorageParams struct {

	/*StorageConfig
	  Create new VM instance

	*/
	StorageConfig models.NewStorage

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create storage params
func (o *CreateStorageParams) WithTimeout(timeout time.Duration) *CreateStorageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create storage params
func (o *CreateStorageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create storage params
func (o *CreateStorageParams) WithContext(ctx context.Context) *CreateStorageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create storage params
func (o *CreateStorageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create storage params
func (o *CreateStorageParams) WithHTTPClient(client *http.Client) *CreateStorageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create storage params
func (o *CreateStorageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithStorageConfig adds the storageConfig to the create storage params
func (o *CreateStorageParams) WithStorageConfig(storageConfig models.NewStorage) *CreateStorageParams {
	o.SetStorageConfig(storageConfig)
	return o
}

// SetStorageConfig adds the storageConfig to the create storage params
func (o *CreateStorageParams) SetStorageConfig(storageConfig models.NewStorage) {
	o.StorageConfig = storageConfig
}

// WriteToRequest writes these params to a swagger request
func (o *CreateStorageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.StorageConfig != nil {
		if err := r.SetBodyParam(o.StorageConfig); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
