// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDestroyStorageParams creates a new DestroyStorageParams object
// with the default values initialized.
func NewDestroyStorageParams() *DestroyStorageParams {
	var ()
	return &DestroyStorageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDestroyStorageParamsWithTimeout creates a new DestroyStorageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDestroyStorageParamsWithTimeout(timeout time.Duration) *DestroyStorageParams {
	var ()
	return &DestroyStorageParams{

		timeout: timeout,
	}
}

// NewDestroyStorageParamsWithContext creates a new DestroyStorageParams object
// with the default values initialized, and the ability to set a context for a request
func NewDestroyStorageParamsWithContext(ctx context.Context) *DestroyStorageParams {
	var ()
	return &DestroyStorageParams{

		Context: ctx,
	}
}

// NewDestroyStorageParamsWithHTTPClient creates a new DestroyStorageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDestroyStorageParamsWithHTTPClient(client *http.Client) *DestroyStorageParams {
	var ()
	return &DestroyStorageParams{
		HTTPClient: client,
	}
}

/*DestroyStorageParams contains all the parameters to send to the API endpoint
for the destroy storage operation typically these are written to a http.Request
*/
type DestroyStorageParams struct {

	/*StorageID
	  ID of VM to return

	*/
	StorageID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the destroy storage params
func (o *DestroyStorageParams) WithTimeout(timeout time.Duration) *DestroyStorageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the destroy storage params
func (o *DestroyStorageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the destroy storage params
func (o *DestroyStorageParams) WithContext(ctx context.Context) *DestroyStorageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the destroy storage params
func (o *DestroyStorageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the destroy storage params
func (o *DestroyStorageParams) WithHTTPClient(client *http.Client) *DestroyStorageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the destroy storage params
func (o *DestroyStorageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithStorageID adds the storageID to the destroy storage params
func (o *DestroyStorageParams) WithStorageID(storageID string) *DestroyStorageParams {
	o.SetStorageID(storageID)
	return o
}

// SetStorageID adds the storageId to the destroy storage params
func (o *DestroyStorageParams) SetStorageID(storageID string) {
	o.StorageID = storageID
}

// WriteToRequest writes these params to a swagger request
func (o *DestroyStorageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param storageID
	if err := r.SetPathParam("storageID", o.StorageID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
