// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/768bit/promethium/api/models"
)

// GetStorageStorageIDKernelsReader is a Reader for the GetStorageStorageIDKernels structure.
type GetStorageStorageIDKernelsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStorageStorageIDKernelsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetStorageStorageIDKernelsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetStorageStorageIDKernelsOK creates a GetStorageStorageIDKernelsOK with default headers values
func NewGetStorageStorageIDKernelsOK() *GetStorageStorageIDKernelsOK {
	return &GetStorageStorageIDKernelsOK{}
}

/*GetStorageStorageIDKernelsOK handles this case with default header values.

OK
*/
type GetStorageStorageIDKernelsOK struct {
	Payload []models.StorageKernel
}

func (o *GetStorageStorageIDKernelsOK) Error() string {
	return fmt.Sprintf("[GET /storage/{storageID}/kernels][%d] getStorageStorageIdKernelsOK  %+v", 200, o.Payload)
}

func (o *GetStorageStorageIDKernelsOK) GetPayload() []models.StorageKernel {
	return o.Payload
}

func (o *GetStorageStorageIDKernelsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
