// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetStorageParams creates a new GetStorageParams object
// with the default values initialized.
func NewGetStorageParams() *GetStorageParams {
	var ()
	return &GetStorageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetStorageParamsWithTimeout creates a new GetStorageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetStorageParamsWithTimeout(timeout time.Duration) *GetStorageParams {
	var ()
	return &GetStorageParams{

		timeout: timeout,
	}
}

// NewGetStorageParamsWithContext creates a new GetStorageParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetStorageParamsWithContext(ctx context.Context) *GetStorageParams {
	var ()
	return &GetStorageParams{

		Context: ctx,
	}
}

// NewGetStorageParamsWithHTTPClient creates a new GetStorageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetStorageParamsWithHTTPClient(client *http.Client) *GetStorageParams {
	var ()
	return &GetStorageParams{
		HTTPClient: client,
	}
}

/*GetStorageParams contains all the parameters to send to the API endpoint
for the get storage operation typically these are written to a http.Request
*/
type GetStorageParams struct {

	/*StorageID
	  ID of Storage to return

	*/
	StorageID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get storage params
func (o *GetStorageParams) WithTimeout(timeout time.Duration) *GetStorageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get storage params
func (o *GetStorageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get storage params
func (o *GetStorageParams) WithContext(ctx context.Context) *GetStorageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get storage params
func (o *GetStorageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get storage params
func (o *GetStorageParams) WithHTTPClient(client *http.Client) *GetStorageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get storage params
func (o *GetStorageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithStorageID adds the storageID to the get storage params
func (o *GetStorageParams) WithStorageID(storageID string) *GetStorageParams {
	o.SetStorageID(storageID)
	return o
}

// SetStorageID adds the storageId to the get storage params
func (o *GetStorageParams) SetStorageID(storageID string) {
	o.StorageID = storageID
}

// WriteToRequest writes these params to a swagger request
func (o *GetStorageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param storageID
	if err := r.SetPathParam("storageID", o.StorageID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
