// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PushImageHandlerFunc turns a function with the right signature into a push image handler
type PushImageHandlerFunc func(PushImageParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PushImageHandlerFunc) Handle(params PushImageParams) middleware.Responder {
	return fn(params)
}

// PushImageHandler interface for that can handle valid push image params
type PushImageHandler interface {
	Handle(PushImageParams) middleware.Responder
}

// NewPushImage creates a new http.Handler for the push image operation
func NewPushImage(ctx *middleware.Context, handler PushImageHandler) *PushImage {
	return &PushImage{Context: ctx, Handler: handler}
}

/*PushImage swagger:route POST /images/push images pushImage

Push an image to the server

Push an image to the server

*/
type PushImage struct {
	Context *middleware.Context
	Handler PushImageHandler
}

func (o *PushImage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPushImageParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
