/*
 * Promethium Daemon API
 *
 * API for Promethium Daemon
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type NewVm struct {
	Name string `json:"name,omitempty"`
	Cpus int64 `json:"cpus,omitempty"`
	Memory int64 `json:"memory,omitempty"`
	Volumes []VmVolume `json:"volumes,omitempty"`
	Drives []VmDrive `json:"drives,omitempty"`
	Interfaces []VmInterface `json:"interfaces,omitempty"`
}
