// Code generated by go-swagger; DO NOT EDIT.

package vms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/768bit/promethium/api/models"
)

// CreateVMOKCode is the HTTP code returned for type CreateVMOK
const CreateVMOKCode int = 200

/*CreateVMOK successful operation

swagger:response createVmOK
*/
type CreateVMOK struct {

	/*
	  In: Body
	*/
	Payload *models.VM `json:"body,omitempty"`
}

// NewCreateVMOK creates CreateVMOK with default headers values
func NewCreateVMOK() *CreateVMOK {

	return &CreateVMOK{}
}

// WithPayload adds the payload to the create Vm o k response
func (o *CreateVMOK) WithPayload(payload *models.VM) *CreateVMOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create Vm o k response
func (o *CreateVMOK) SetPayload(payload *models.VM) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateVMOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateVMBadRequestCode is the HTTP code returned for type CreateVMBadRequest
const CreateVMBadRequestCode int = 400

/*CreateVMBadRequest Invalid ID supplied

swagger:response createVmBadRequest
*/
type CreateVMBadRequest struct {
}

// NewCreateVMBadRequest creates CreateVMBadRequest with default headers values
func NewCreateVMBadRequest() *CreateVMBadRequest {

	return &CreateVMBadRequest{}
}

// WriteResponse to the client
func (o *CreateVMBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// CreateVMNotFoundCode is the HTTP code returned for type CreateVMNotFound
const CreateVMNotFoundCode int = 404

/*CreateVMNotFound VM not found

swagger:response createVmNotFound
*/
type CreateVMNotFound struct {
}

// NewCreateVMNotFound creates CreateVMNotFound with default headers values
func NewCreateVMNotFound() *CreateVMNotFound {

	return &CreateVMNotFound{}
}

// WriteResponse to the client
func (o *CreateVMNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
