// Code generated by go-swagger; DO NOT EDIT.

package vms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/768bit/promethium/api/models"
)

// GetVMDiskListOKCode is the HTTP code returned for type GetVMDiskListOK
const GetVMDiskListOKCode int = 200

/*GetVMDiskListOK Array of Disks

swagger:response getVmDiskListOK
*/
type GetVMDiskListOK struct {

	/*
	  In: Body
	*/
	Payload []*models.VMDisk `json:"body,omitempty"`
}

// NewGetVMDiskListOK creates GetVMDiskListOK with default headers values
func NewGetVMDiskListOK() *GetVMDiskListOK {

	return &GetVMDiskListOK{}
}

// WithPayload adds the payload to the get Vm disk list o k response
func (o *GetVMDiskListOK) WithPayload(payload []*models.VMDisk) *GetVMDiskListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Vm disk list o k response
func (o *GetVMDiskListOK) SetPayload(payload []*models.VMDisk) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVMDiskListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.VMDisk, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetVMDiskListDefault unexpected error

swagger:response getVmDiskListDefault
*/
type GetVMDiskListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetVMDiskListDefault creates GetVMDiskListDefault with default headers values
func NewGetVMDiskListDefault(code int) *GetVMDiskListDefault {
	if code <= 0 {
		code = 500
	}

	return &GetVMDiskListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get VM disk list default response
func (o *GetVMDiskListDefault) WithStatusCode(code int) *GetVMDiskListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get VM disk list default response
func (o *GetVMDiskListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get VM disk list default response
func (o *GetVMDiskListDefault) WithPayload(payload *models.Error) *GetVMDiskListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get VM disk list default response
func (o *GetVMDiskListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVMDiskListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
