// Code generated by go-swagger; DO NOT EDIT.

package vms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetVMInteraceHandlerFunc turns a function with the right signature into a get VM interace handler
type GetVMInteraceHandlerFunc func(GetVMInteraceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetVMInteraceHandlerFunc) Handle(params GetVMInteraceParams) middleware.Responder {
	return fn(params)
}

// GetVMInteraceHandler interface for that can handle valid get VM interace params
type GetVMInteraceHandler interface {
	Handle(GetVMInteraceParams) middleware.Responder
}

// NewGetVMInterace creates a new http.Handler for the get VM interace operation
func NewGetVMInterace(ctx *middleware.Context, handler GetVMInteraceHandler) *GetVMInterace {
	return &GetVMInterace{Context: ctx, Handler: handler}
}

/*GetVMInterace swagger:route GET /vms/{vmID}/interfaces/{interfaceID} vms getVmInterace

Return a VM Network Interface

Returns an instance of VM Network Interface

*/
type GetVMInterace struct {
	Context *middleware.Context
	Handler GetVMInteraceHandler
}

func (o *GetVMInterace) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetVMInteraceParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
