// Code generated by go-swagger; DO NOT EDIT.

package vms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/768bit/promethium/api/models"
)

// GetVMVolumeListOKCode is the HTTP code returned for type GetVMVolumeListOK
const GetVMVolumeListOKCode int = 200

/*GetVMVolumeListOK Array of VM Volumes

swagger:response getVmVolumeListOK
*/
type GetVMVolumeListOK struct {

	/*
	  In: Body
	*/
	Payload []*models.VMVolume `json:"body,omitempty"`
}

// NewGetVMVolumeListOK creates GetVMVolumeListOK with default headers values
func NewGetVMVolumeListOK() *GetVMVolumeListOK {

	return &GetVMVolumeListOK{}
}

// WithPayload adds the payload to the get Vm volume list o k response
func (o *GetVMVolumeListOK) WithPayload(payload []*models.VMVolume) *GetVMVolumeListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Vm volume list o k response
func (o *GetVMVolumeListOK) SetPayload(payload []*models.VMVolume) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVMVolumeListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.VMVolume, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetVMVolumeListDefault unexpected error

swagger:response getVmVolumeListDefault
*/
type GetVMVolumeListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetVMVolumeListDefault creates GetVMVolumeListDefault with default headers values
func NewGetVMVolumeListDefault(code int) *GetVMVolumeListDefault {
	if code <= 0 {
		code = 500
	}

	return &GetVMVolumeListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get VM volume list default response
func (o *GetVMVolumeListDefault) WithStatusCode(code int) *GetVMVolumeListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get VM volume list default response
func (o *GetVMVolumeListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get VM volume list default response
func (o *GetVMVolumeListDefault) WithPayload(payload *models.Error) *GetVMVolumeListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get VM volume list default response
func (o *GetVMVolumeListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVMVolumeListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
