// Code generated by go-swagger; DO NOT EDIT.

package vms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/768bit/promethium/api/models"
)

// RestartVMOKCode is the HTTP code returned for type RestartVMOK
const RestartVMOKCode int = 200

/*RestartVMOK successful operation

swagger:response restartVmOK
*/
type RestartVMOK struct {

	/*
	  In: Body
	*/
	Payload *models.VM `json:"body,omitempty"`
}

// NewRestartVMOK creates RestartVMOK with default headers values
func NewRestartVMOK() *RestartVMOK {

	return &RestartVMOK{}
}

// WithPayload adds the payload to the restart Vm o k response
func (o *RestartVMOK) WithPayload(payload *models.VM) *RestartVMOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the restart Vm o k response
func (o *RestartVMOK) SetPayload(payload *models.VM) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RestartVMOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RestartVMBadRequestCode is the HTTP code returned for type RestartVMBadRequest
const RestartVMBadRequestCode int = 400

/*RestartVMBadRequest Invalid ID supplied

swagger:response restartVmBadRequest
*/
type RestartVMBadRequest struct {
}

// NewRestartVMBadRequest creates RestartVMBadRequest with default headers values
func NewRestartVMBadRequest() *RestartVMBadRequest {

	return &RestartVMBadRequest{}
}

// WriteResponse to the client
func (o *RestartVMBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// RestartVMNotFoundCode is the HTTP code returned for type RestartVMNotFound
const RestartVMNotFoundCode int = 404

/*RestartVMNotFound VM not found

swagger:response restartVmNotFound
*/
type RestartVMNotFound struct {
}

// NewRestartVMNotFound creates RestartVMNotFound with default headers values
func NewRestartVMNotFound() *RestartVMNotFound {

	return &RestartVMNotFound{}
}

// WriteResponse to the client
func (o *RestartVMNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
