// Code generated by go-swagger; DO NOT EDIT.

package vms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/768bit/promethium/api/models"
)

// ShutdownVMOKCode is the HTTP code returned for type ShutdownVMOK
const ShutdownVMOKCode int = 200

/*ShutdownVMOK successful operation

swagger:response shutdownVmOK
*/
type ShutdownVMOK struct {

	/*
	  In: Body
	*/
	Payload *models.VM `json:"body,omitempty"`
}

// NewShutdownVMOK creates ShutdownVMOK with default headers values
func NewShutdownVMOK() *ShutdownVMOK {

	return &ShutdownVMOK{}
}

// WithPayload adds the payload to the shutdown Vm o k response
func (o *ShutdownVMOK) WithPayload(payload *models.VM) *ShutdownVMOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the shutdown Vm o k response
func (o *ShutdownVMOK) SetPayload(payload *models.VM) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShutdownVMOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ShutdownVMBadRequestCode is the HTTP code returned for type ShutdownVMBadRequest
const ShutdownVMBadRequestCode int = 400

/*ShutdownVMBadRequest Invalid ID supplied

swagger:response shutdownVmBadRequest
*/
type ShutdownVMBadRequest struct {
}

// NewShutdownVMBadRequest creates ShutdownVMBadRequest with default headers values
func NewShutdownVMBadRequest() *ShutdownVMBadRequest {

	return &ShutdownVMBadRequest{}
}

// WriteResponse to the client
func (o *ShutdownVMBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// ShutdownVMNotFoundCode is the HTTP code returned for type ShutdownVMNotFound
const ShutdownVMNotFoundCode int = 404

/*ShutdownVMNotFound VM not found

swagger:response shutdownVmNotFound
*/
type ShutdownVMNotFound struct {
}

// NewShutdownVMNotFound creates ShutdownVMNotFound with default headers values
func NewShutdownVMNotFound() *ShutdownVMNotFound {

	return &ShutdownVMNotFound{}
}

// WriteResponse to the client
func (o *ShutdownVMNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
