// Code generated by go-swagger; DO NOT EDIT.

package vms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateVMInterfaceHandlerFunc turns a function with the right signature into a update VM interface handler
type UpdateVMInterfaceHandlerFunc func(UpdateVMInterfaceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateVMInterfaceHandlerFunc) Handle(params UpdateVMInterfaceParams) middleware.Responder {
	return fn(params)
}

// UpdateVMInterfaceHandler interface for that can handle valid update VM interface params
type UpdateVMInterfaceHandler interface {
	Handle(UpdateVMInterfaceParams) middleware.Responder
}

// NewUpdateVMInterface creates a new http.Handler for the update VM interface operation
func NewUpdateVMInterface(ctx *middleware.Context, handler UpdateVMInterfaceHandler) *UpdateVMInterface {
	return &UpdateVMInterface{Context: ctx, Handler: handler}
}

/*UpdateVMInterface swagger:route PUT /vms/{vmID}/interfaces/{interfaceID} vms updateVmInterface

Update a VM Network Interface instance

Update an instance of VM Network Interface

*/
type UpdateVMInterface struct {
	Context *middleware.Context
	Handler UpdateVMInterfaceHandler
}

func (o *UpdateVMInterface) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateVMInterfaceParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
