// Code generated by go-swagger; DO NOT EDIT.

package vms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateVMDiskHandlerFunc turns a function with the right signature into a update VM disk handler
type UpdateVMDiskHandlerFunc func(UpdateVMDiskParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateVMDiskHandlerFunc) Handle(params UpdateVMDiskParams) middleware.Responder {
	return fn(params)
}

// UpdateVMDiskHandler interface for that can handle valid update VM disk params
type UpdateVMDiskHandler interface {
	Handle(UpdateVMDiskParams) middleware.Responder
}

// NewUpdateVMDisk creates a new http.Handler for the update VM disk operation
func NewUpdateVMDisk(ctx *middleware.Context, handler UpdateVMDiskHandler) *UpdateVMDisk {
	return &UpdateVMDisk{Context: ctx, Handler: handler}
}

/*UpdateVMDisk swagger:route PUT /vms/{vmID}/disks/{diskID} vms updateVmDisk

Update a VM Interface instance

Update an instance of VM interface

*/
type UpdateVMDisk struct {
	Context *middleware.Context
	Handler UpdateVMDiskHandler
}

func (o *UpdateVMDisk) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateVMDiskParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
