// Code generated by go-swagger; DO NOT EDIT.

package vms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/768bit/promethium/api/models"
)

// NewUpdateVMInterfaceParams creates a new UpdateVMInterfaceParams object
// no default values defined in spec.
func NewUpdateVMInterfaceParams() UpdateVMInterfaceParams {

	return UpdateVMInterfaceParams{}
}

// UpdateVMInterfaceParams contains all the bound params for the update VM interface operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateVMInterface
type UpdateVMInterfaceParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*ID of VM Interface to use
	  Required: true
	  In: path
	*/
	InterfaceID string
	/*ID of VM to return
	  Required: true
	  In: path
	*/
	VMID string
	/*Updated VM Interface Config
	  Required: true
	  In: body
	*/
	VMInterfaceConfig *models.UpdateVMInterface
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateVMInterfaceParams() beforehand.
func (o *UpdateVMInterfaceParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rInterfaceID, rhkInterfaceID, _ := route.Params.GetOK("interfaceID")
	if err := o.bindInterfaceID(rInterfaceID, rhkInterfaceID, route.Formats); err != nil {
		res = append(res, err)
	}

	rVMID, rhkVMID, _ := route.Params.GetOK("vmID")
	if err := o.bindVMID(rVMID, rhkVMID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.UpdateVMInterface
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("vmInterfaceConfig", "body"))
			} else {
				res = append(res, errors.NewParseError("vmInterfaceConfig", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.VMInterfaceConfig = &body
			}
		}
	} else {
		res = append(res, errors.Required("vmInterfaceConfig", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindInterfaceID binds and validates parameter InterfaceID from path.
func (o *UpdateVMInterfaceParams) bindInterfaceID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.InterfaceID = raw

	return nil
}

// bindVMID binds and validates parameter VMID from path.
func (o *UpdateVMInterfaceParams) bindVMID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.VMID = raw

	return nil
}
