// Code generated by go-swagger; DO NOT EDIT.

package vms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// UpdateVMInterfaceURL generates an URL for the update VM interface operation
type UpdateVMInterfaceURL struct {
	InterfaceID string
	VMID        string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *UpdateVMInterfaceURL) WithBasePath(bp string) *UpdateVMInterfaceURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *UpdateVMInterfaceURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *UpdateVMInterfaceURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/vms/{vmID}/interfaces/{interfaceID}"

	interfaceID := o.InterfaceID
	if interfaceID != "" {
		_path = strings.Replace(_path, "{interfaceID}", interfaceID, -1)
	} else {
		return nil, errors.New("interfaceId is required on UpdateVMInterfaceURL")
	}

	vMID := o.VMID
	if vMID != "" {
		_path = strings.Replace(_path, "{vmID}", vMID, -1)
	} else {
		return nil, errors.New("vmId is required on UpdateVMInterfaceURL")
	}

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *UpdateVMInterfaceURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *UpdateVMInterfaceURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *UpdateVMInterfaceURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on UpdateVMInterfaceURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on UpdateVMInterfaceURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *UpdateVMInterfaceURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
