// Code generated by go-swagger; DO NOT EDIT.

package vms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/768bit/promethium/api/models"
)

// NewCreateVMInterfaceParams creates a new CreateVMInterfaceParams object
// with the default values initialized.
func NewCreateVMInterfaceParams() *CreateVMInterfaceParams {
	var ()
	return &CreateVMInterfaceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateVMInterfaceParamsWithTimeout creates a new CreateVMInterfaceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateVMInterfaceParamsWithTimeout(timeout time.Duration) *CreateVMInterfaceParams {
	var ()
	return &CreateVMInterfaceParams{

		timeout: timeout,
	}
}

// NewCreateVMInterfaceParamsWithContext creates a new CreateVMInterfaceParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateVMInterfaceParamsWithContext(ctx context.Context) *CreateVMInterfaceParams {
	var ()
	return &CreateVMInterfaceParams{

		Context: ctx,
	}
}

// NewCreateVMInterfaceParamsWithHTTPClient creates a new CreateVMInterfaceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateVMInterfaceParamsWithHTTPClient(client *http.Client) *CreateVMInterfaceParams {
	var ()
	return &CreateVMInterfaceParams{
		HTTPClient: client,
	}
}

/*CreateVMInterfaceParams contains all the parameters to send to the API endpoint
for the create VM interface operation typically these are written to a http.Request
*/
type CreateVMInterfaceParams struct {

	/*InterfaceConfig
	  Create new VM instance

	*/
	InterfaceConfig *models.NewVMInterface
	/*VMID
	  ID of VM to use

	*/
	VMID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create VM interface params
func (o *CreateVMInterfaceParams) WithTimeout(timeout time.Duration) *CreateVMInterfaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create VM interface params
func (o *CreateVMInterfaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create VM interface params
func (o *CreateVMInterfaceParams) WithContext(ctx context.Context) *CreateVMInterfaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create VM interface params
func (o *CreateVMInterfaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create VM interface params
func (o *CreateVMInterfaceParams) WithHTTPClient(client *http.Client) *CreateVMInterfaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create VM interface params
func (o *CreateVMInterfaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInterfaceConfig adds the interfaceConfig to the create VM interface params
func (o *CreateVMInterfaceParams) WithInterfaceConfig(interfaceConfig *models.NewVMInterface) *CreateVMInterfaceParams {
	o.SetInterfaceConfig(interfaceConfig)
	return o
}

// SetInterfaceConfig adds the interfaceConfig to the create VM interface params
func (o *CreateVMInterfaceParams) SetInterfaceConfig(interfaceConfig *models.NewVMInterface) {
	o.InterfaceConfig = interfaceConfig
}

// WithVMID adds the vMID to the create VM interface params
func (o *CreateVMInterfaceParams) WithVMID(vMID string) *CreateVMInterfaceParams {
	o.SetVMID(vMID)
	return o
}

// SetVMID adds the vmId to the create VM interface params
func (o *CreateVMInterfaceParams) SetVMID(vMID string) {
	o.VMID = vMID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateVMInterfaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.InterfaceConfig != nil {
		if err := r.SetBodyParam(o.InterfaceConfig); err != nil {
			return err
		}
	}

	// path param vmID
	if err := r.SetPathParam("vmID", o.VMID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
