// Code generated by go-swagger; DO NOT EDIT.

package vms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteVMInterfaceParams creates a new DeleteVMInterfaceParams object
// with the default values initialized.
func NewDeleteVMInterfaceParams() *DeleteVMInterfaceParams {
	var ()
	return &DeleteVMInterfaceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteVMInterfaceParamsWithTimeout creates a new DeleteVMInterfaceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteVMInterfaceParamsWithTimeout(timeout time.Duration) *DeleteVMInterfaceParams {
	var ()
	return &DeleteVMInterfaceParams{

		timeout: timeout,
	}
}

// NewDeleteVMInterfaceParamsWithContext creates a new DeleteVMInterfaceParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteVMInterfaceParamsWithContext(ctx context.Context) *DeleteVMInterfaceParams {
	var ()
	return &DeleteVMInterfaceParams{

		Context: ctx,
	}
}

// NewDeleteVMInterfaceParamsWithHTTPClient creates a new DeleteVMInterfaceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteVMInterfaceParamsWithHTTPClient(client *http.Client) *DeleteVMInterfaceParams {
	var ()
	return &DeleteVMInterfaceParams{
		HTTPClient: client,
	}
}

/*DeleteVMInterfaceParams contains all the parameters to send to the API endpoint
for the delete VM interface operation typically these are written to a http.Request
*/
type DeleteVMInterfaceParams struct {

	/*InterfaceID
	  ID of VM Interface to use

	*/
	InterfaceID string
	/*VMID
	  ID of VM to return

	*/
	VMID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete VM interface params
func (o *DeleteVMInterfaceParams) WithTimeout(timeout time.Duration) *DeleteVMInterfaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete VM interface params
func (o *DeleteVMInterfaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete VM interface params
func (o *DeleteVMInterfaceParams) WithContext(ctx context.Context) *DeleteVMInterfaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete VM interface params
func (o *DeleteVMInterfaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete VM interface params
func (o *DeleteVMInterfaceParams) WithHTTPClient(client *http.Client) *DeleteVMInterfaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete VM interface params
func (o *DeleteVMInterfaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInterfaceID adds the interfaceID to the delete VM interface params
func (o *DeleteVMInterfaceParams) WithInterfaceID(interfaceID string) *DeleteVMInterfaceParams {
	o.SetInterfaceID(interfaceID)
	return o
}

// SetInterfaceID adds the interfaceId to the delete VM interface params
func (o *DeleteVMInterfaceParams) SetInterfaceID(interfaceID string) {
	o.InterfaceID = interfaceID
}

// WithVMID adds the vMID to the delete VM interface params
func (o *DeleteVMInterfaceParams) WithVMID(vMID string) *DeleteVMInterfaceParams {
	o.SetVMID(vMID)
	return o
}

// SetVMID adds the vmId to the delete VM interface params
func (o *DeleteVMInterfaceParams) SetVMID(vMID string) {
	o.VMID = vMID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteVMInterfaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param interfaceID
	if err := r.SetPathParam("interfaceID", o.InterfaceID); err != nil {
		return err
	}

	// path param vmID
	if err := r.SetPathParam("vmID", o.VMID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
