// Code generated by go-swagger; DO NOT EDIT.

package vms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteVMParams creates a new DeleteVMParams object
// with the default values initialized.
func NewDeleteVMParams() *DeleteVMParams {
	var ()
	return &DeleteVMParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteVMParamsWithTimeout creates a new DeleteVMParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteVMParamsWithTimeout(timeout time.Duration) *DeleteVMParams {
	var ()
	return &DeleteVMParams{

		timeout: timeout,
	}
}

// NewDeleteVMParamsWithContext creates a new DeleteVMParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteVMParamsWithContext(ctx context.Context) *DeleteVMParams {
	var ()
	return &DeleteVMParams{

		Context: ctx,
	}
}

// NewDeleteVMParamsWithHTTPClient creates a new DeleteVMParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteVMParamsWithHTTPClient(client *http.Client) *DeleteVMParams {
	var ()
	return &DeleteVMParams{
		HTTPClient: client,
	}
}

/*DeleteVMParams contains all the parameters to send to the API endpoint
for the delete VM operation typically these are written to a http.Request
*/
type DeleteVMParams struct {

	/*VMID
	  ID of VM to return

	*/
	VMID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete VM params
func (o *DeleteVMParams) WithTimeout(timeout time.Duration) *DeleteVMParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete VM params
func (o *DeleteVMParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete VM params
func (o *DeleteVMParams) WithContext(ctx context.Context) *DeleteVMParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete VM params
func (o *DeleteVMParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete VM params
func (o *DeleteVMParams) WithHTTPClient(client *http.Client) *DeleteVMParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete VM params
func (o *DeleteVMParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVMID adds the vMID to the delete VM params
func (o *DeleteVMParams) WithVMID(vMID string) *DeleteVMParams {
	o.SetVMID(vMID)
	return o
}

// SetVMID adds the vmId to the delete VM params
func (o *DeleteVMParams) SetVMID(vMID string) {
	o.VMID = vMID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteVMParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param vmID
	if err := r.SetPathParam("vmID", o.VMID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
