// Code generated by go-swagger; DO NOT EDIT.

package vms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetVMVolumeParams creates a new GetVMVolumeParams object
// with the default values initialized.
func NewGetVMVolumeParams() *GetVMVolumeParams {
	var ()
	return &GetVMVolumeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetVMVolumeParamsWithTimeout creates a new GetVMVolumeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetVMVolumeParamsWithTimeout(timeout time.Duration) *GetVMVolumeParams {
	var ()
	return &GetVMVolumeParams{

		timeout: timeout,
	}
}

// NewGetVMVolumeParamsWithContext creates a new GetVMVolumeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetVMVolumeParamsWithContext(ctx context.Context) *GetVMVolumeParams {
	var ()
	return &GetVMVolumeParams{

		Context: ctx,
	}
}

// NewGetVMVolumeParamsWithHTTPClient creates a new GetVMVolumeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetVMVolumeParamsWithHTTPClient(client *http.Client) *GetVMVolumeParams {
	var ()
	return &GetVMVolumeParams{
		HTTPClient: client,
	}
}

/*GetVMVolumeParams contains all the parameters to send to the API endpoint
for the get VM volume operation typically these are written to a http.Request
*/
type GetVMVolumeParams struct {

	/*VMID
	  ID of VM to return

	*/
	VMID string
	/*VolumeID
	  ID of VM Volume to use

	*/
	VolumeID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get VM volume params
func (o *GetVMVolumeParams) WithTimeout(timeout time.Duration) *GetVMVolumeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get VM volume params
func (o *GetVMVolumeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get VM volume params
func (o *GetVMVolumeParams) WithContext(ctx context.Context) *GetVMVolumeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get VM volume params
func (o *GetVMVolumeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get VM volume params
func (o *GetVMVolumeParams) WithHTTPClient(client *http.Client) *GetVMVolumeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get VM volume params
func (o *GetVMVolumeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVMID adds the vMID to the get VM volume params
func (o *GetVMVolumeParams) WithVMID(vMID string) *GetVMVolumeParams {
	o.SetVMID(vMID)
	return o
}

// SetVMID adds the vmId to the get VM volume params
func (o *GetVMVolumeParams) SetVMID(vMID string) {
	o.VMID = vMID
}

// WithVolumeID adds the volumeID to the get VM volume params
func (o *GetVMVolumeParams) WithVolumeID(volumeID string) *GetVMVolumeParams {
	o.SetVolumeID(volumeID)
	return o
}

// SetVolumeID adds the volumeId to the get VM volume params
func (o *GetVMVolumeParams) SetVolumeID(volumeID string) {
	o.VolumeID = volumeID
}

// WriteToRequest writes these params to a swagger request
func (o *GetVMVolumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param vmID
	if err := r.SetPathParam("vmID", o.VMID); err != nil {
		return err
	}

	// path param volumeID
	if err := r.SetPathParam("volumeID", o.VolumeID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
