// Code generated by go-swagger; DO NOT EDIT.

package vms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetVMDiskParams creates a new GetVMDiskParams object
// with the default values initialized.
func NewGetVMDiskParams() *GetVMDiskParams {
	var ()
	return &GetVMDiskParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetVMDiskParamsWithTimeout creates a new GetVMDiskParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetVMDiskParamsWithTimeout(timeout time.Duration) *GetVMDiskParams {
	var ()
	return &GetVMDiskParams{

		timeout: timeout,
	}
}

// NewGetVMDiskParamsWithContext creates a new GetVMDiskParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetVMDiskParamsWithContext(ctx context.Context) *GetVMDiskParams {
	var ()
	return &GetVMDiskParams{

		Context: ctx,
	}
}

// NewGetVMDiskParamsWithHTTPClient creates a new GetVMDiskParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetVMDiskParamsWithHTTPClient(client *http.Client) *GetVMDiskParams {
	var ()
	return &GetVMDiskParams{
		HTTPClient: client,
	}
}

/*GetVMDiskParams contains all the parameters to send to the API endpoint
for the get VM disk operation typically these are written to a http.Request
*/
type GetVMDiskParams struct {

	/*DiskID
	  ID of VM Disk to use

	*/
	DiskID string
	/*VMID
	  ID of VM to return

	*/
	VMID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get VM disk params
func (o *GetVMDiskParams) WithTimeout(timeout time.Duration) *GetVMDiskParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get VM disk params
func (o *GetVMDiskParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get VM disk params
func (o *GetVMDiskParams) WithContext(ctx context.Context) *GetVMDiskParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get VM disk params
func (o *GetVMDiskParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get VM disk params
func (o *GetVMDiskParams) WithHTTPClient(client *http.Client) *GetVMDiskParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get VM disk params
func (o *GetVMDiskParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDiskID adds the diskID to the get VM disk params
func (o *GetVMDiskParams) WithDiskID(diskID string) *GetVMDiskParams {
	o.SetDiskID(diskID)
	return o
}

// SetDiskID adds the diskId to the get VM disk params
func (o *GetVMDiskParams) SetDiskID(diskID string) {
	o.DiskID = diskID
}

// WithVMID adds the vMID to the get VM disk params
func (o *GetVMDiskParams) WithVMID(vMID string) *GetVMDiskParams {
	o.SetVMID(vMID)
	return o
}

// SetVMID adds the vmId to the get VM disk params
func (o *GetVMDiskParams) SetVMID(vMID string) {
	o.VMID = vMID
}

// WriteToRequest writes these params to a swagger request
func (o *GetVMDiskParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param diskID
	if err := r.SetPathParam("diskID", o.DiskID); err != nil {
		return err
	}

	// path param vmID
	if err := r.SetPathParam("vmID", o.VMID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
