// Code generated by go-swagger; DO NOT EDIT.

package vms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewResetVMParams creates a new ResetVMParams object
// with the default values initialized.
func NewResetVMParams() *ResetVMParams {
	var ()
	return &ResetVMParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewResetVMParamsWithTimeout creates a new ResetVMParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewResetVMParamsWithTimeout(timeout time.Duration) *ResetVMParams {
	var ()
	return &ResetVMParams{

		timeout: timeout,
	}
}

// NewResetVMParamsWithContext creates a new ResetVMParams object
// with the default values initialized, and the ability to set a context for a request
func NewResetVMParamsWithContext(ctx context.Context) *ResetVMParams {
	var ()
	return &ResetVMParams{

		Context: ctx,
	}
}

// NewResetVMParamsWithHTTPClient creates a new ResetVMParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewResetVMParamsWithHTTPClient(client *http.Client) *ResetVMParams {
	var ()
	return &ResetVMParams{
		HTTPClient: client,
	}
}

/*ResetVMParams contains all the parameters to send to the API endpoint
for the reset VM operation typically these are written to a http.Request
*/
type ResetVMParams struct {

	/*VMID
	  ID of VM to return

	*/
	VMID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the reset VM params
func (o *ResetVMParams) WithTimeout(timeout time.Duration) *ResetVMParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the reset VM params
func (o *ResetVMParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the reset VM params
func (o *ResetVMParams) WithContext(ctx context.Context) *ResetVMParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the reset VM params
func (o *ResetVMParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the reset VM params
func (o *ResetVMParams) WithHTTPClient(client *http.Client) *ResetVMParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the reset VM params
func (o *ResetVMParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVMID adds the vMID to the reset VM params
func (o *ResetVMParams) WithVMID(vMID string) *ResetVMParams {
	o.SetVMID(vMID)
	return o
}

// SetVMID adds the vmId to the reset VM params
func (o *ResetVMParams) SetVMID(vMID string) {
	o.VMID = vMID
}

// WriteToRequest writes these params to a swagger request
func (o *ResetVMParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param vmID
	if err := r.SetPathParam("vmID", o.VMID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
