// Code generated by go-swagger; DO NOT EDIT.

package vms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/768bit/promethium/api/models"
)

// RestartVMReader is a Reader for the RestartVM structure.
type RestartVMReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RestartVMReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRestartVMOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRestartVMBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRestartVMNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRestartVMOK creates a RestartVMOK with default headers values
func NewRestartVMOK() *RestartVMOK {
	return &RestartVMOK{}
}

/*RestartVMOK handles this case with default header values.

successful operation
*/
type RestartVMOK struct {
	Payload *models.VM
}

func (o *RestartVMOK) Error() string {
	return fmt.Sprintf("[GET /vms/{vmID}/restart][%d] restartVmOK  %+v", 200, o.Payload)
}

func (o *RestartVMOK) GetPayload() *models.VM {
	return o.Payload
}

func (o *RestartVMOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VM)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRestartVMBadRequest creates a RestartVMBadRequest with default headers values
func NewRestartVMBadRequest() *RestartVMBadRequest {
	return &RestartVMBadRequest{}
}

/*RestartVMBadRequest handles this case with default header values.

Invalid ID supplied
*/
type RestartVMBadRequest struct {
}

func (o *RestartVMBadRequest) Error() string {
	return fmt.Sprintf("[GET /vms/{vmID}/restart][%d] restartVmBadRequest ", 400)
}

func (o *RestartVMBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRestartVMNotFound creates a RestartVMNotFound with default headers values
func NewRestartVMNotFound() *RestartVMNotFound {
	return &RestartVMNotFound{}
}

/*RestartVMNotFound handles this case with default header values.

VM not found
*/
type RestartVMNotFound struct {
}

func (o *RestartVMNotFound) Error() string {
	return fmt.Sprintf("[GET /vms/{vmID}/restart][%d] restartVmNotFound ", 404)
}

func (o *RestartVMNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
