// Code generated by go-swagger; DO NOT EDIT.

package vms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRestartVMParams creates a new RestartVMParams object
// with the default values initialized.
func NewRestartVMParams() *RestartVMParams {
	var ()
	return &RestartVMParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRestartVMParamsWithTimeout creates a new RestartVMParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRestartVMParamsWithTimeout(timeout time.Duration) *RestartVMParams {
	var ()
	return &RestartVMParams{

		timeout: timeout,
	}
}

// NewRestartVMParamsWithContext creates a new RestartVMParams object
// with the default values initialized, and the ability to set a context for a request
func NewRestartVMParamsWithContext(ctx context.Context) *RestartVMParams {
	var ()
	return &RestartVMParams{

		Context: ctx,
	}
}

// NewRestartVMParamsWithHTTPClient creates a new RestartVMParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRestartVMParamsWithHTTPClient(client *http.Client) *RestartVMParams {
	var ()
	return &RestartVMParams{
		HTTPClient: client,
	}
}

/*RestartVMParams contains all the parameters to send to the API endpoint
for the restart VM operation typically these are written to a http.Request
*/
type RestartVMParams struct {

	/*VMID
	  ID of VM to return

	*/
	VMID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the restart VM params
func (o *RestartVMParams) WithTimeout(timeout time.Duration) *RestartVMParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the restart VM params
func (o *RestartVMParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the restart VM params
func (o *RestartVMParams) WithContext(ctx context.Context) *RestartVMParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the restart VM params
func (o *RestartVMParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the restart VM params
func (o *RestartVMParams) WithHTTPClient(client *http.Client) *RestartVMParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the restart VM params
func (o *RestartVMParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVMID adds the vMID to the restart VM params
func (o *RestartVMParams) WithVMID(vMID string) *RestartVMParams {
	o.SetVMID(vMID)
	return o
}

// SetVMID adds the vmId to the restart VM params
func (o *RestartVMParams) SetVMID(vMID string) {
	o.VMID = vMID
}

// WriteToRequest writes these params to a swagger request
func (o *RestartVMParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param vmID
	if err := r.SetPathParam("vmID", o.VMID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
