// Code generated by go-swagger; DO NOT EDIT.

package vms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewShutdownVMParams creates a new ShutdownVMParams object
// with the default values initialized.
func NewShutdownVMParams() *ShutdownVMParams {
	var ()
	return &ShutdownVMParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewShutdownVMParamsWithTimeout creates a new ShutdownVMParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewShutdownVMParamsWithTimeout(timeout time.Duration) *ShutdownVMParams {
	var ()
	return &ShutdownVMParams{

		timeout: timeout,
	}
}

// NewShutdownVMParamsWithContext creates a new ShutdownVMParams object
// with the default values initialized, and the ability to set a context for a request
func NewShutdownVMParamsWithContext(ctx context.Context) *ShutdownVMParams {
	var ()
	return &ShutdownVMParams{

		Context: ctx,
	}
}

// NewShutdownVMParamsWithHTTPClient creates a new ShutdownVMParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewShutdownVMParamsWithHTTPClient(client *http.Client) *ShutdownVMParams {
	var ()
	return &ShutdownVMParams{
		HTTPClient: client,
	}
}

/*ShutdownVMParams contains all the parameters to send to the API endpoint
for the shutdown VM operation typically these are written to a http.Request
*/
type ShutdownVMParams struct {

	/*VMID
	  ID of VM to return

	*/
	VMID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the shutdown VM params
func (o *ShutdownVMParams) WithTimeout(timeout time.Duration) *ShutdownVMParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the shutdown VM params
func (o *ShutdownVMParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the shutdown VM params
func (o *ShutdownVMParams) WithContext(ctx context.Context) *ShutdownVMParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the shutdown VM params
func (o *ShutdownVMParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the shutdown VM params
func (o *ShutdownVMParams) WithHTTPClient(client *http.Client) *ShutdownVMParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the shutdown VM params
func (o *ShutdownVMParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVMID adds the vMID to the shutdown VM params
func (o *ShutdownVMParams) WithVMID(vMID string) *ShutdownVMParams {
	o.SetVMID(vMID)
	return o
}

// SetVMID adds the vmId to the shutdown VM params
func (o *ShutdownVMParams) SetVMID(vMID string) {
	o.VMID = vMID
}

// WriteToRequest writes these params to a swagger request
func (o *ShutdownVMParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param vmID
	if err := r.SetPathParam("vmID", o.VMID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
