// Code generated by go-swagger; DO NOT EDIT.

package vms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStartVMParams creates a new StartVMParams object
// with the default values initialized.
func NewStartVMParams() *StartVMParams {
	var ()
	return &StartVMParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStartVMParamsWithTimeout creates a new StartVMParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStartVMParamsWithTimeout(timeout time.Duration) *StartVMParams {
	var ()
	return &StartVMParams{

		timeout: timeout,
	}
}

// NewStartVMParamsWithContext creates a new StartVMParams object
// with the default values initialized, and the ability to set a context for a request
func NewStartVMParamsWithContext(ctx context.Context) *StartVMParams {
	var ()
	return &StartVMParams{

		Context: ctx,
	}
}

// NewStartVMParamsWithHTTPClient creates a new StartVMParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStartVMParamsWithHTTPClient(client *http.Client) *StartVMParams {
	var ()
	return &StartVMParams{
		HTTPClient: client,
	}
}

/*StartVMParams contains all the parameters to send to the API endpoint
for the start VM operation typically these are written to a http.Request
*/
type StartVMParams struct {

	/*VMID
	  ID of VM to return

	*/
	VMID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the start VM params
func (o *StartVMParams) WithTimeout(timeout time.Duration) *StartVMParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the start VM params
func (o *StartVMParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the start VM params
func (o *StartVMParams) WithContext(ctx context.Context) *StartVMParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the start VM params
func (o *StartVMParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the start VM params
func (o *StartVMParams) WithHTTPClient(client *http.Client) *StartVMParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the start VM params
func (o *StartVMParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVMID adds the vMID to the start VM params
func (o *StartVMParams) WithVMID(vMID string) *StartVMParams {
	o.SetVMID(vMID)
	return o
}

// SetVMID adds the vmId to the start VM params
func (o *StartVMParams) SetVMID(vMID string) {
	o.VMID = vMID
}

// WriteToRequest writes these params to a swagger request
func (o *StartVMParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param vmID
	if err := r.SetPathParam("vmID", o.VMID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
