// Code generated by go-swagger; DO NOT EDIT.

package networking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/768bit/promethium/api/models"
)

// DestroyNetworkReader is a Reader for the DestroyNetwork structure.
type DestroyNetworkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DestroyNetworkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDestroyNetworkOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDestroyNetworkOK creates a DestroyNetworkOK with default headers values
func NewDestroyNetworkOK() *DestroyNetworkOK {
	return &DestroyNetworkOK{}
}

/*DestroyNetworkOK handles this case with default header values.

successful operation
*/
type DestroyNetworkOK struct {
	Payload *models.Network
}

func (o *DestroyNetworkOK) Error() string {
	return fmt.Sprintf("[DELETE /networking/{networkID}][%d] destroyNetworkOK  %+v", 200, o.Payload)
}

func (o *DestroyNetworkOK) GetPayload() *models.Network {
	return o.Payload
}

func (o *DestroyNetworkOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Network)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
