// Code generated by go-swagger; DO NOT EDIT.

package networking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDestroyNetworkParams creates a new DestroyNetworkParams object
// with the default values initialized.
func NewDestroyNetworkParams() *DestroyNetworkParams {
	var ()
	return &DestroyNetworkParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDestroyNetworkParamsWithTimeout creates a new DestroyNetworkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDestroyNetworkParamsWithTimeout(timeout time.Duration) *DestroyNetworkParams {
	var ()
	return &DestroyNetworkParams{

		timeout: timeout,
	}
}

// NewDestroyNetworkParamsWithContext creates a new DestroyNetworkParams object
// with the default values initialized, and the ability to set a context for a request
func NewDestroyNetworkParamsWithContext(ctx context.Context) *DestroyNetworkParams {
	var ()
	return &DestroyNetworkParams{

		Context: ctx,
	}
}

// NewDestroyNetworkParamsWithHTTPClient creates a new DestroyNetworkParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDestroyNetworkParamsWithHTTPClient(client *http.Client) *DestroyNetworkParams {
	var ()
	return &DestroyNetworkParams{
		HTTPClient: client,
	}
}

/*DestroyNetworkParams contains all the parameters to send to the API endpoint
for the destroy network operation typically these are written to a http.Request
*/
type DestroyNetworkParams struct {

	/*NetworkID
	  ID of Network to delete

	*/
	NetworkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the destroy network params
func (o *DestroyNetworkParams) WithTimeout(timeout time.Duration) *DestroyNetworkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the destroy network params
func (o *DestroyNetworkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the destroy network params
func (o *DestroyNetworkParams) WithContext(ctx context.Context) *DestroyNetworkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the destroy network params
func (o *DestroyNetworkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the destroy network params
func (o *DestroyNetworkParams) WithHTTPClient(client *http.Client) *DestroyNetworkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the destroy network params
func (o *DestroyNetworkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetworkID adds the networkID to the destroy network params
func (o *DestroyNetworkParams) WithNetworkID(networkID string) *DestroyNetworkParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the destroy network params
func (o *DestroyNetworkParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WriteToRequest writes these params to a swagger request
func (o *DestroyNetworkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param networkID
	if err := r.SetPathParam("networkID", o.NetworkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
