// Code generated by go-swagger; DO NOT EDIT.

package networking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/768bit/promethium/api/models"
)

// GetNetworkInterfacesReader is a Reader for the GetNetworkInterfaces structure.
type GetNetworkInterfacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkInterfacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkInterfacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNetworkInterfacesOK creates a GetNetworkInterfacesOK with default headers values
func NewGetNetworkInterfacesOK() *GetNetworkInterfacesOK {
	return &GetNetworkInterfacesOK{}
}

/*GetNetworkInterfacesOK handles this case with default header values.

OK
*/
type GetNetworkInterfacesOK struct {
	Payload []models.NetworkInterface
}

func (o *GetNetworkInterfacesOK) Error() string {
	return fmt.Sprintf("[GET /networking/{networkID}/interfaces][%d] getNetworkInterfacesOK  %+v", 200, o.Payload)
}

func (o *GetNetworkInterfacesOK) GetPayload() []models.NetworkInterface {
	return o.Payload
}

func (o *GetNetworkInterfacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
