// Code generated by go-swagger; DO NOT EDIT.

package networking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetNetworkInterfacesParams creates a new GetNetworkInterfacesParams object
// with the default values initialized.
func NewGetNetworkInterfacesParams() *GetNetworkInterfacesParams {
	var ()
	return &GetNetworkInterfacesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetNetworkInterfacesParamsWithTimeout creates a new GetNetworkInterfacesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetNetworkInterfacesParamsWithTimeout(timeout time.Duration) *GetNetworkInterfacesParams {
	var ()
	return &GetNetworkInterfacesParams{

		timeout: timeout,
	}
}

// NewGetNetworkInterfacesParamsWithContext creates a new GetNetworkInterfacesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetNetworkInterfacesParamsWithContext(ctx context.Context) *GetNetworkInterfacesParams {
	var ()
	return &GetNetworkInterfacesParams{

		Context: ctx,
	}
}

// NewGetNetworkInterfacesParamsWithHTTPClient creates a new GetNetworkInterfacesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetNetworkInterfacesParamsWithHTTPClient(client *http.Client) *GetNetworkInterfacesParams {
	var ()
	return &GetNetworkInterfacesParams{
		HTTPClient: client,
	}
}

/*GetNetworkInterfacesParams contains all the parameters to send to the API endpoint
for the get network interfaces operation typically these are written to a http.Request
*/
type GetNetworkInterfacesParams struct {

	/*NetworkID
	  ID of VM to return

	*/
	NetworkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get network interfaces params
func (o *GetNetworkInterfacesParams) WithTimeout(timeout time.Duration) *GetNetworkInterfacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get network interfaces params
func (o *GetNetworkInterfacesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get network interfaces params
func (o *GetNetworkInterfacesParams) WithContext(ctx context.Context) *GetNetworkInterfacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get network interfaces params
func (o *GetNetworkInterfacesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get network interfaces params
func (o *GetNetworkInterfacesParams) WithHTTPClient(client *http.Client) *GetNetworkInterfacesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get network interfaces params
func (o *GetNetworkInterfacesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetworkID adds the networkID to the get network interfaces params
func (o *GetNetworkInterfacesParams) WithNetworkID(networkID string) *GetNetworkInterfacesParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the get network interfaces params
func (o *GetNetworkInterfacesParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WriteToRequest writes these params to a swagger request
func (o *GetNetworkInterfacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param networkID
	if err := r.SetPathParam("networkID", o.NetworkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
