// Code generated by go-swagger; DO NOT EDIT.

package networking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/768bit/promethium/api/models"
)

// GetPhysicalInterfacesReader is a Reader for the GetPhysicalInterfaces structure.
type GetPhysicalInterfacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPhysicalInterfacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPhysicalInterfacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPhysicalInterfacesOK creates a GetPhysicalInterfacesOK with default headers values
func NewGetPhysicalInterfacesOK() *GetPhysicalInterfacesOK {
	return &GetPhysicalInterfacesOK{}
}

/*GetPhysicalInterfacesOK handles this case with default header values.

OK
*/
type GetPhysicalInterfacesOK struct {
	Payload []*models.PhysicalInterface
}

func (o *GetPhysicalInterfacesOK) Error() string {
	return fmt.Sprintf("[GET /networking/physicalInterfaces][%d] getPhysicalInterfacesOK  %+v", 200, o.Payload)
}

func (o *GetPhysicalInterfacesOK) GetPayload() []*models.PhysicalInterface {
	return o.Payload
}

func (o *GetPhysicalInterfacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
