// Code generated by go-swagger; DO NOT EDIT.

package networking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/768bit/promethium/api/models"
)

// GetNetworkListReader is a Reader for the GetNetworkList structure.
type GetNetworkListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNetworkListOK creates a GetNetworkListOK with default headers values
func NewGetNetworkListOK() *GetNetworkListOK {
	return &GetNetworkListOK{}
}

/*GetNetworkListOK handles this case with default header values.

OK
*/
type GetNetworkListOK struct {
	Payload []models.Network
}

func (o *GetNetworkListOK) Error() string {
	return fmt.Sprintf("[GET /networking][%d] getNetworkListOK  %+v", 200, o.Payload)
}

func (o *GetNetworkListOK) GetPayload() []models.Network {
	return o.Payload
}

func (o *GetNetworkListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
