// Code generated by go-swagger; DO NOT EDIT.

package networking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/768bit/promethium/api/models"
)

// CreateNetworkOKCode is the HTTP code returned for type CreateNetworkOK
const CreateNetworkOKCode int = 200

/*CreateNetworkOK successful operation

swagger:response createNetworkOK
*/
type CreateNetworkOK struct {

	/*
	  In: Body
	*/
	Payload models.Network `json:"body,omitempty"`
}

// NewCreateNetworkOK creates CreateNetworkOK with default headers values
func NewCreateNetworkOK() *CreateNetworkOK {

	return &CreateNetworkOK{}
}

// WithPayload adds the payload to the create network o k response
func (o *CreateNetworkOK) WithPayload(payload models.Network) *CreateNetworkOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create network o k response
func (o *CreateNetworkOK) SetPayload(payload models.Network) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateNetworkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
