// Code generated by go-swagger; DO NOT EDIT.

package networking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateNetworkHandlerFunc turns a function with the right signature into a update network handler
type UpdateNetworkHandlerFunc func(UpdateNetworkParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateNetworkHandlerFunc) Handle(params UpdateNetworkParams) middleware.Responder {
	return fn(params)
}

// UpdateNetworkHandler interface for that can handle valid update network params
type UpdateNetworkHandler interface {
	Handle(UpdateNetworkParams) middleware.Responder
}

// NewUpdateNetwork creates a new http.Handler for the update network operation
func NewUpdateNetwork(ctx *middleware.Context, handler UpdateNetworkHandler) *UpdateNetwork {
	return &UpdateNetwork{Context: ctx, Handler: handler}
}

/*UpdateNetwork swagger:route PUT /networking/{networkID} networking updateNetwork

Update network

*/
type UpdateNetwork struct {
	Context *middleware.Context
	Handler UpdateNetworkHandler
}

func (o *UpdateNetwork) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateNetworkParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
