// Code generated by go-swagger; DO NOT EDIT.

package networking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/768bit/promethium/api/models"
)

// UpdateNetworkOKCode is the HTTP code returned for type UpdateNetworkOK
const UpdateNetworkOKCode int = 200

/*UpdateNetworkOK successful operation

swagger:response updateNetworkOK
*/
type UpdateNetworkOK struct {

	/*
	  In: Body
	*/
	Payload *models.Network `json:"body,omitempty"`
}

// NewUpdateNetworkOK creates UpdateNetworkOK with default headers values
func NewUpdateNetworkOK() *UpdateNetworkOK {

	return &UpdateNetworkOK{}
}

// WithPayload adds the payload to the update network o k response
func (o *UpdateNetworkOK) WithPayload(payload *models.Network) *UpdateNetworkOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update network o k response
func (o *UpdateNetworkOK) SetPayload(payload *models.Network) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateNetworkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateNetworkBadRequestCode is the HTTP code returned for type UpdateNetworkBadRequest
const UpdateNetworkBadRequestCode int = 400

/*UpdateNetworkBadRequest Invalid ID supplied

swagger:response updateNetworkBadRequest
*/
type UpdateNetworkBadRequest struct {
}

// NewUpdateNetworkBadRequest creates UpdateNetworkBadRequest with default headers values
func NewUpdateNetworkBadRequest() *UpdateNetworkBadRequest {

	return &UpdateNetworkBadRequest{}
}

// WriteResponse to the client
func (o *UpdateNetworkBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateNetworkNotFoundCode is the HTTP code returned for type UpdateNetworkNotFound
const UpdateNetworkNotFoundCode int = 404

/*UpdateNetworkNotFound Storage not found

swagger:response updateNetworkNotFound
*/
type UpdateNetworkNotFound struct {
}

// NewUpdateNetworkNotFound creates UpdateNetworkNotFound with default headers values
func NewUpdateNetworkNotFound() *UpdateNetworkNotFound {

	return &UpdateNetworkNotFound{}
}

// WriteResponse to the client
func (o *UpdateNetworkNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
