// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/768bit/promethium/api/models"
)

// GetStorageStorageIDImagesOKCode is the HTTP code returned for type GetStorageStorageIDImagesOK
const GetStorageStorageIDImagesOKCode int = 200

/*GetStorageStorageIDImagesOK OK

swagger:response getStorageStorageIdImagesOK
*/
type GetStorageStorageIDImagesOK struct {

	/*
	  In: Body
	*/
	Payload []models.StorageImage `json:"body,omitempty"`
}

// NewGetStorageStorageIDImagesOK creates GetStorageStorageIDImagesOK with default headers values
func NewGetStorageStorageIDImagesOK() *GetStorageStorageIDImagesOK {

	return &GetStorageStorageIDImagesOK{}
}

// WithPayload adds the payload to the get storage storage Id images o k response
func (o *GetStorageStorageIDImagesOK) WithPayload(payload []models.StorageImage) *GetStorageStorageIDImagesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get storage storage Id images o k response
func (o *GetStorageStorageIDImagesOK) SetPayload(payload []models.StorageImage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStorageStorageIDImagesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]models.StorageImage, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
