// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/768bit/promethium/api/models"
)

// GetStorageStorageIDDisksOKCode is the HTTP code returned for type GetStorageStorageIDDisksOK
const GetStorageStorageIDDisksOKCode int = 200

/*GetStorageStorageIDDisksOK OK

swagger:response getStorageStorageIdDisksOK
*/
type GetStorageStorageIDDisksOK struct {

	/*
	  In: Body
	*/
	Payload []models.StorageDisk `json:"body,omitempty"`
}

// NewGetStorageStorageIDDisksOK creates GetStorageStorageIDDisksOK with default headers values
func NewGetStorageStorageIDDisksOK() *GetStorageStorageIDDisksOK {

	return &GetStorageStorageIDDisksOK{}
}

// WithPayload adds the payload to the get storage storage Id disks o k response
func (o *GetStorageStorageIDDisksOK) WithPayload(payload []models.StorageDisk) *GetStorageStorageIDDisksOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get storage storage Id disks o k response
func (o *GetStorageStorageIDDisksOK) SetPayload(payload []models.StorageDisk) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStorageStorageIDDisksOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]models.StorageDisk, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
