// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/768bit/promethium/api/models"
)

// NewUpdateStorageParams creates a new UpdateStorageParams object
// no default values defined in spec.
func NewUpdateStorageParams() UpdateStorageParams {

	return UpdateStorageParams{}
}

// UpdateStorageParams contains all the bound params for the update storage operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateStorage
type UpdateStorageParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Create new VM instance
	  Required: true
	  In: body
	*/
	StorageConfig models.UpdateStorage
	/*ID of VM to return
	  Required: true
	  In: path
	*/
	StorageID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateStorageParams() beforehand.
func (o *UpdateStorageParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.UpdateStorage
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("storageConfig", "body"))
			} else {
				res = append(res, errors.NewParseError("storageConfig", "body", "", err))
			}
		} else {
			// no validation on generic interface
			o.StorageConfig = body
		}
	} else {
		res = append(res, errors.Required("storageConfig", "body"))
	}
	rStorageID, rhkStorageID, _ := route.Params.GetOK("storageID")
	if err := o.bindStorageID(rStorageID, rhkStorageID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindStorageID binds and validates parameter StorageID from path.
func (o *UpdateStorageParams) bindStorageID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.StorageID = raw

	return nil
}
