// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ImagePushPullTarget image push pull target
// swagger:model ImagePushPullTarget
type ImagePushPullTarget struct {

	// blob
	// Format: binary
	Blob io.ReadCloser `json:"Blob,omitempty"`

	// source URI
	SourceURI string `json:"SourceURI,omitempty"`

	// target storage
	TargetStorage string `json:"TargetStorage,omitempty"`
}

// Validate validates this image push pull target
func (m *ImagePushPullTarget) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImagePushPullTarget) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImagePushPullTarget) UnmarshalBinary(b []byte) error {
	var res ImagePushPullTarget
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
