// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// KernelImage kernel image
// swagger:model KernelImage
type KernelImage struct {

	// hash
	Hash string `json:"Hash,omitempty"`

	// size
	Size int64 `json:"Size,omitempty"`
}

// Validate validates this kernel image
func (m *KernelImage) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *KernelImage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KernelImage) UnmarshalBinary(b []byte) error {
	var res KernelImage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
