// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MetaDataNetworkEthernetsMatchConfig meta data network ethernets match config
// swagger:model MetaDataNetworkEthernetsMatchConfig
type MetaDataNetworkEthernetsMatchConfig struct {

	// driver
	Driver string `json:"driver,omitempty"`

	// macaddress
	Macaddress string `json:"macaddress,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this meta data network ethernets match config
func (m *MetaDataNetworkEthernetsMatchConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MetaDataNetworkEthernetsMatchConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetaDataNetworkEthernetsMatchConfig) UnmarshalBinary(b []byte) error {
	var res MetaDataNetworkEthernetsMatchConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
