// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MetaDataNetworkRoutesConfig meta data network routes config
// swagger:model MetaDataNetworkRoutesConfig
type MetaDataNetworkRoutesConfig struct {

	// metric
	Metric int32 `json:"metric,omitempty"`

	// to
	To string `json:"to,omitempty"`

	// via
	Via string `json:"via,omitempty"`
}

// Validate validates this meta data network routes config
func (m *MetaDataNetworkRoutesConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MetaDataNetworkRoutesConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetaDataNetworkRoutesConfig) UnmarshalBinary(b []byte) error {
	var res MetaDataNetworkRoutesConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
