// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// MetaDataNetworkInterfaceConfig meta data network interface config
// swagger:model MetaDataNetworkInterfaceConfig
type MetaDataNetworkInterfaceConfig struct {

	// config
	Config *MetaDataNetworkEthernetsConfig `json:"config,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// mac address
	MacAddress string `json:"macAddress,omitempty"`

	// network ID
	NetworkID string `json:"networkID,omitempty"`
}

// Validate validates this meta data network interface config
func (m *MetaDataNetworkInterfaceConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConfig(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MetaDataNetworkInterfaceConfig) validateConfig(formats strfmt.Registry) error {

	if swag.IsZero(m.Config) { // not required
		return nil
	}

	if m.Config != nil {
		if err := m.Config.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("config")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MetaDataNetworkInterfaceConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetaDataNetworkInterfaceConfig) UnmarshalBinary(b []byte) error {
	var res MetaDataNetworkInterfaceConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
