// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PhysicalInterface physical interface
// swagger:model PhysicalInterface
type PhysicalInterface struct {

	// addresses
	Addresses []string `json:"addresses"`

	// mac address
	MacAddress string `json:"macAddress,omitempty"`

	// mtu
	Mtu int32 `json:"mtu,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this physical interface
func (m *PhysicalInterface) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PhysicalInterface) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PhysicalInterface) UnmarshalBinary(b []byte) error {
	var res PhysicalInterface
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
