// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// VMInterface VM interface
// swagger:model VMInterface
type VMInterface struct {

	// config
	Config interface{} `json:"config,omitempty"`

	// id
	// Format: uuid4
	ID strfmt.UUID4 `json:"id,omitempty"`

	// network ID
	// Format: uuid4
	NetworkID strfmt.UUID4 `json:"networkID,omitempty"`
}

// Validate validates this VM interface
func (m *VMInterface) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNetworkID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VMInterface) validateID(formats strfmt.Registry) error {

	if swag.IsZero(m.ID) { // not required
		return nil
	}

	if err := validate.FormatOf("id", "body", "uuid4", m.ID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *VMInterface) validateNetworkID(formats strfmt.Registry) error {

	if swag.IsZero(m.NetworkID) { // not required
		return nil
	}

	if err := validate.FormatOf("networkID", "body", "uuid4", m.NetworkID.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *VMInterface) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VMInterface) UnmarshalBinary(b []byte) error {
	var res VMInterface
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
