// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/768bit/promethium/api/models"
)

// GetImagesListReader is a Reader for the GetImagesList structure.
type GetImagesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetImagesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetImagesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetImagesListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetImagesListOK creates a GetImagesListOK with default headers values
func NewGetImagesListOK() *GetImagesListOK {
	return &GetImagesListOK{}
}

/*GetImagesListOK handles this case with default header values.

Array of Images
*/
type GetImagesListOK struct {
	Payload []*models.Image
}

func (o *GetImagesListOK) Error() string {
	return fmt.Sprintf("[GET /images][%d] getImagesListOK  %+v", 200, o.Payload)
}

func (o *GetImagesListOK) GetPayload() []*models.Image {
	return o.Payload
}

func (o *GetImagesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetImagesListDefault creates a GetImagesListDefault with default headers values
func NewGetImagesListDefault(code int) *GetImagesListDefault {
	return &GetImagesListDefault{
		_statusCode: code,
	}
}

/*GetImagesListDefault handles this case with default header values.

unexpected error
*/
type GetImagesListDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get images list default response
func (o *GetImagesListDefault) Code() int {
	return o._statusCode
}

func (o *GetImagesListDefault) Error() string {
	return fmt.Sprintf("[GET /images][%d] getImagesList default  %+v", o._statusCode, o.Payload)
}

func (o *GetImagesListDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetImagesListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
